apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:

      nodeSelector:
        kubernetes.io/hostname: worker-node

      containers:
      - name: backend

        image: vishalv26/electronix-backend:v2

        imagePullPolicy: Always

        ports:
        - containerPort: 5000

        env:

        - name: DB_HOST
          value: mysql

        - name: DB_PORT
          value: "3306"

        - name: DB_NAME
          value: ecommerce_db

        - name: DB_USER
          value: root

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD

        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"