apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: electronix-ingress
  namespace: electronix
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

spec:
  ingressClassName: nginx

  rules:
  - host: electronix.vvlabs.info
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80

  - host: api.electronix.vvlabs.info
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: backend
            port:
              number: 5000